model_name: gpt2
train_file_path: ./data/comment.txt
output_dir: ./result
overwrite_output_dir: False
per_device_train_batch_size: 8
num_train_epochs: 5
save_steps: 500
pretrained_model_path: ./model_path
use_trainer: False
# use_trainer: True

# train_file_path: /content/drive/MyDrive/data/comment.txt
# model_name: gpt2
# output_dir: /content/drive/MyDrive/result
# overwrite_output_dir: False
# per_device_train_batch_size: 8
# num_train_epochs: 5.0
# save_steps: 500